# monitoring/prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "porttrack-app"
    static_configs:
      - targets: ["porttrack-app:8080"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
